# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SiKKuRo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SiKKuRo

  target 'SiKKuRoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'SnapKit'
  target 'SiKKuRoUITests' do
    # Pods for testing
  end

end
